--[[
================================================================================
ROBLOX ADMIN PANEL — Single-File Edition
================================================================================
A complete client-side admin panel. Everything is generated by this one file:
the ScreenGui, the tween animations, the command logic, and the respawn
handling. Drop it in as a LocalScript (StarterPlayer > StarterPlayerScripts)
or run it through an executor.

QUICK START
  1. Open the CONFIG block below.
  2. Set Owner to your username and (optionally) add Whitelist entries.
  3. Run the script.
  4. Press the keybind (default RightControl) — or tap the floating button
     on mobile — to toggle the panel.

NOTES
  • This panel is fully client-side. No RemoteEvents and no Server Script
    are required, which keeps setup beginner-friendly. Commands that target
    other players (Bring / Freeze / etc.) only have a visible effect in
    experiences where the engine allows client-driven physics; on
    FilteringEnabled servers those effects will revert.
  • All toggle state is preserved across respawns automatically.
================================================================================
]]

-- ─── CONFIGURATION ──────────────────────────────────────────────────────────
local CONFIG = {
    Owner         = "",                              -- Owner username. "" = whoever runs the script.
    Whitelist     = { },                             -- Extra usernames, e.g. {"Friend1", "Friend2"}
    Ranks         = {                                -- Optional rank labels shown in logs
        -- ["Username"] = "Admin",
    },
    Keybind       = Enum.KeyCode.RightControl,       -- Toggle key for the panel
    CommandPrefix = "/",                             -- Prefix for the in-panel command bar
    AccentColor   = Color3.fromRGB(99, 132, 255),    -- Primary accent
    PanelTitle    = "ADMIN PANEL",
    ShowMobileButton = true,                         -- Floating toggle button on touch devices
}

-- ─── SERVICES ───────────────────────────────────────────────────────────────
local Players          = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService       = game:GetService("RunService")
local TweenService     = game:GetService("TweenService")
local Lighting         = game:GetService("Lighting")
local Workspace        = game:GetService("Workspace")
local CoreGui          = game:GetService("CoreGui")
local GuiService       = game:GetService("GuiService")
local HttpService      = game:GetService("HttpService")

local LocalPlayer = Players.LocalPlayer
local Camera      = Workspace.CurrentCamera

-- ─── ACCESS CHECK ───────────────────────────────────────────────────────────
local function isAuthorized(player)
    if CONFIG.Owner == "" then return true end
    if player.Name == CONFIG.Owner then return true end
    for _, name in ipairs(CONFIG.Whitelist) do
        if name == player.Name then return true end
    end
    return false
end

if not isAuthorized(LocalPlayer) then return end

-- ─── GUI PARENT RESOLUTION ──────────────────────────────────────────────────
-- Prefer CoreGui-protected variants when running via executor, fall back to
-- PlayerGui in Studio / vanilla LocalScript contexts.
local function resolveGuiParent()
    local candidates = {}
    if typeof(gethui) == "function" then table.insert(candidates, gethui) end
    if typeof(get_hidden_gui) == "function" then table.insert(candidates, get_hidden_gui) end
    for _, fn in ipairs(candidates) do
        local ok, parent = pcall(fn)
        if ok and parent then return parent end
    end
    local ok = pcall(function() return CoreGui:GetChildren() end)
    if ok then return CoreGui end
    return LocalPlayer:WaitForChild("PlayerGui")
end

-- Wipe any previous instance so re-running the script doesn't stack panels.
local existing = resolveGuiParent():FindFirstChild("AdminPanel")
if existing then existing:Destroy() end

-- ─── SHARED STATE ───────────────────────────────────────────────────────────
-- Every toggle command writes here. Respawn handlers re-apply from this table.
local State = {
    flying         = false,
    flySpeed       = 60,
    noclipping     = false,
    walkSpeed      = 16,
    walkSpeedOn    = false,
    jumpPower      = 50,
    jumpPowerOn    = false,
    infJump        = false,
    invisible      = false,
    godMode        = false,
    spectating     = nil,                            -- Player instance or nil
    selectedPlayer = nil,                            -- Player instance for player-tab actions
    frozen         = {},                             -- [Player] = oldCFrame
    vehicleSpeed   = 1,
    vehicleBoost   = false,
    vehicleInsta   = false,
    vehicleFly     = false,
    fov            = 70,
    gravity        = 196.2,
    timeOfDay      = nil,                            -- Lighting.ClockTime override or nil
    espOn          = false,
    tracersOn      = false,
    fullbrightOn   = false,
}

-- Stores connections / instances keyed by feature name for clean teardown.
local Active = {}
local Log    = {}

-- ─── UTILITIES ──────────────────────────────────────────────────────────────
local function make(class, props, children)
    local inst = Instance.new(class)
    local parent
    for k, v in pairs(props or {}) do
        if k == "Parent" then parent = v else inst[k] = v end
    end
    for _, c in ipairs(children or {}) do c.Parent = inst end
    if parent then inst.Parent = parent end
    return inst
end

local function tween(obj, info, props)
    local t = TweenService:Create(obj, info, props)
    t:Play()
    return t
end

local QuickTween   = TweenInfo.new(0.18, Enum.EasingStyle.Quart, Enum.EasingDirection.Out)
local SmoothTween  = TweenInfo.new(0.30, Enum.EasingStyle.Quart, Enum.EasingDirection.Out)
local BounceTween  = TweenInfo.new(0.35, Enum.EasingStyle.Back,  Enum.EasingDirection.Out)

local function character()
    return LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()
end

local function getHumanoid(char)
    char = char or LocalPlayer.Character
    return char and char:FindFirstChildOfClass("Humanoid")
end

local function getHRP(char)
    char = char or LocalPlayer.Character
    return char and char:FindFirstChild("HumanoidRootPart")
end

local function rank(name)
    if name == CONFIG.Owner then return "Owner" end
    if CONFIG.Ranks[name] then return CONFIG.Ranks[name] end
    for _, n in ipairs(CONFIG.Whitelist) do
        if n == name then return "Admin" end
    end
    return "Guest"
end

-- ─── ROOT GUI ───────────────────────────────────────────────────────────────
local gui = make("ScreenGui", {
    Name              = "AdminPanel",
    ResetOnSpawn      = false,
    IgnoreGuiInset    = true,
    ZIndexBehavior    = Enum.ZIndexBehavior.Sibling,
    DisplayOrder      = 9999,
    Parent            = resolveGuiParent(),
})

-- Top-level layers: panel + notifications + ESP highlights + tracers
local notifLayer = make("Frame", {
    Name                   = "Notifications",
    AnchorPoint            = Vector2.new(1, 0),
    Position               = UDim2.new(1, -16, 0, 16),
    Size                   = UDim2.new(0, 280, 1, -32),
    BackgroundTransparency = 1,
    Parent                 = gui,
})
make("UIListLayout", {
    Padding              = UDim.new(0, 8),
    HorizontalAlignment  = Enum.HorizontalAlignment.Right,
    SortOrder            = Enum.SortOrder.LayoutOrder,
    Parent               = notifLayer,
})

local tracerLayer = make("Frame", {
    Name                   = "Tracers",
    Size                   = UDim2.fromScale(1, 1),
    BackgroundTransparency = 1,
    Visible                = true,
    Parent                 = gui,
})

-- ─── NOTIFICATIONS ──────────────────────────────────────────────────────────
local function notify(text, kind)
    kind = kind or "info"
    local color = ({
        info  = Color3.fromRGB(99, 132, 255),
        ok    = Color3.fromRGB(70, 200, 120),
        warn  = Color3.fromRGB(230, 170, 50),
        err   = Color3.fromRGB(230, 80, 80),
    })[kind] or CONFIG.AccentColor

    local box = make("Frame", {
        BackgroundColor3       = Color3.fromRGB(20, 22, 28),
        BackgroundTransparency = 0.05,
        Size                   = UDim2.new(1, 0, 0, 0),     -- height set by AutomaticSize
        AutomaticSize          = Enum.AutomaticSize.Y,
        Position               = UDim2.new(1, 0, 0, 0),
        Parent                 = notifLayer,
    })
    make("UICorner",  { CornerRadius = UDim.new(0, 8), Parent = box })
    make("UIStroke",  { Color = Color3.fromRGB(40, 44, 52), Transparency = 0.4, Thickness = 1, Parent = box })
    make("Frame", {                                          -- accent stripe
        BackgroundColor3       = color,
        BorderSizePixel        = 0,
        Size                   = UDim2.new(0, 3, 1, -10),
        Position               = UDim2.new(0, 6, 0, 5),
        Parent                 = box,
    })
    make("TextLabel", {
        BackgroundTransparency = 1,
        Position               = UDim2.new(0, 18, 0, 6),
        Size                   = UDim2.new(1, -28, 1, -12),
        Font                   = Enum.Font.Gotham,
        Text                   = text,
        TextColor3             = Color3.fromRGB(235, 235, 240),
        TextSize               = 13,
        TextWrapped            = true,
        TextXAlignment         = Enum.TextXAlignment.Left,
        TextYAlignment         = Enum.TextYAlignment.Center,
        AutomaticSize          = Enum.AutomaticSize.Y,
        Parent                 = box,
    })

    box.Position = UDim2.new(1.2, 0, 0, 0)
    tween(box, BounceTween, { Position = UDim2.new(0, 0, 0, 0) })

    task.delay(3.6, function()
        if not box.Parent then return end
        local t = tween(box, QuickTween, {
            Position               = UDim2.new(1.2, 0, 0, 0),
            BackgroundTransparency = 1,
        })
        t.Completed:Wait()
        box:Destroy()
    end)
end

local function logCmd(text)
    local stamp = os.date("%H:%M:%S")
    table.insert(Log, ("[%s] %s"):format(stamp, text))
    if #Log > 200 then table.remove(Log, 1) end
end

-- ─── MAIN PANEL ─────────────────────────────────────────────────────────────
local panel = make("Frame", {
    Name                   = "Panel",
    AnchorPoint            = Vector2.new(0.5, 0.5),
    Position               = UDim2.fromScale(0.5, 0.5),
    Size                   = UDim2.fromOffset(620, 420),
    BackgroundColor3       = Color3.fromRGB(15, 17, 22),
    BackgroundTransparency = 0.05,
    BorderSizePixel        = 0,
    Visible                = false,
    Active                 = true,
    Parent                 = gui,
})
make("UICorner", { CornerRadius = UDim.new(0, 12), Parent = panel })
make("UIStroke", {
    Color        = Color3.fromRGB(40, 44, 56),
    Thickness    = 1,
    Transparency = 0.3,
    Parent       = panel,
})
-- Subtle gradient backdrop for depth
make("UIGradient", {
    Rotation = 90,
    Color    = ColorSequence.new({
        ColorSequenceKeypoint.new(0,   Color3.fromRGB(25, 28, 36)),
        ColorSequenceKeypoint.new(1,   Color3.fromRGB(12, 13, 18)),
    }),
    Parent   = panel,
})

-- ── Title bar ──────────────────────────────────────────────────────────────
local titleBar = make("Frame", {
    Name                   = "TitleBar",
    BackgroundTransparency = 1,
    Size                   = UDim2.new(1, 0, 0, 40),
    Parent                 = panel,
})
make("TextLabel", {
    Name                   = "Title",
    BackgroundTransparency = 1,
    Position               = UDim2.new(0, 16, 0, 0),
    Size                   = UDim2.new(0.5, 0, 1, 0),
    Font                   = Enum.Font.GothamBold,
    Text                   = CONFIG.PanelTitle,
    TextColor3             = Color3.fromRGB(240, 240, 250),
    TextSize               = 15,
    TextXAlignment         = Enum.TextXAlignment.Left,
    Parent                 = titleBar,
})
make("TextLabel", {
    Name                   = "Subtitle",
    BackgroundTransparency = 1,
    Position               = UDim2.new(0, 16, 0, 22),
    Size                   = UDim2.new(0.5, 0, 0, 14),
    Font                   = Enum.Font.Gotham,
    Text                   = ("%s · %s"):format(LocalPlayer.Name, rank(LocalPlayer.Name)),
    TextColor3             = Color3.fromRGB(140, 145, 160),
    TextSize               = 11,
    TextXAlignment         = Enum.TextXAlignment.Left,
    Parent                 = titleBar,
})

local function makeTitleButton(name, text, offsetX, hoverColor)
    local b = make("TextButton", {
        Name                   = name,
        AnchorPoint            = Vector2.new(1, 0.5),
        Position               = UDim2.new(1, offsetX, 0.5, 0),
        Size                   = UDim2.fromOffset(26, 26),
        BackgroundColor3       = Color3.fromRGB(30, 33, 42),
        BackgroundTransparency = 0.2,
        BorderSizePixel        = 0,
        Font                   = Enum.Font.GothamBold,
        Text                   = text,
        TextColor3             = Color3.fromRGB(220, 220, 230),
        TextSize               = 14,
        AutoButtonColor        = false,
        Parent                 = titleBar,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = b })
    b.MouseEnter:Connect(function() tween(b, QuickTween, { BackgroundColor3 = hoverColor }) end)
    b.MouseLeave:Connect(function() tween(b, QuickTween, { BackgroundColor3 = Color3.fromRGB(30, 33, 42) }) end)
    return b
end

local closeBtn    = makeTitleButton("Close",    "×", -10,  Color3.fromRGB(220, 70, 70))
local minimizeBtn = makeTitleButton("Minimize", "–", -42,  Color3.fromRGB(60, 65, 80))

-- ── Sidebar (tabs) ─────────────────────────────────────────────────────────
local sidebar = make("Frame", {
    Name                   = "Sidebar",
    BackgroundColor3       = Color3.fromRGB(11, 13, 17),
    BackgroundTransparency = 0.1,
    BorderSizePixel        = 0,
    Position               = UDim2.new(0, 8, 0, 48),
    Size                   = UDim2.new(0, 130, 1, -94),
    Parent                 = panel,
})
make("UICorner", { CornerRadius = UDim.new(0, 8), Parent = sidebar })
make("UIPadding", {
    PaddingTop = UDim.new(0, 8), PaddingBottom = UDim.new(0, 8),
    PaddingLeft = UDim.new(0, 6), PaddingRight = UDim.new(0, 6),
    Parent = sidebar,
})
make("UIListLayout", {
    Padding   = UDim.new(0, 4),
    SortOrder = Enum.SortOrder.LayoutOrder,
    Parent    = sidebar,
})

-- ── Content area ───────────────────────────────────────────────────────────
local content = make("Frame", {
    Name                   = "Content",
    BackgroundColor3       = Color3.fromRGB(11, 13, 17),
    BackgroundTransparency = 0.15,
    BorderSizePixel        = 0,
    Position               = UDim2.new(0, 146, 0, 48),
    Size                   = UDim2.new(1, -154, 1, -94),
    ClipsDescendants       = true,
    Parent                 = panel,
})
make("UICorner", { CornerRadius = UDim.new(0, 8), Parent = content })

-- ── Command bar ────────────────────────────────────────────────────────────
local cmdBar = make("Frame", {
    Name                   = "CommandBar",
    BackgroundColor3       = Color3.fromRGB(11, 13, 17),
    BackgroundTransparency = 0.1,
    BorderSizePixel        = 0,
    Position               = UDim2.new(0, 8, 1, -38),
    Size                   = UDim2.new(1, -16, 0, 30),
    Parent                 = panel,
})
make("UICorner", { CornerRadius = UDim.new(0, 8), Parent = cmdBar })
make("UIStroke", { Color = Color3.fromRGB(35, 38, 48), Transparency = 0.4, Parent = cmdBar })

make("TextLabel", {
    BackgroundTransparency = 1,
    Position               = UDim2.new(0, 10, 0, 0),
    Size                   = UDim2.new(0, 14, 1, 0),
    Font                   = Enum.Font.GothamBold,
    Text                   = CONFIG.CommandPrefix,
    TextColor3             = CONFIG.AccentColor,
    TextSize               = 14,
    Parent                 = cmdBar,
})
local cmdInput = make("TextBox", {
    BackgroundTransparency = 1,
    Position               = UDim2.new(0, 28, 0, 0),
    Size                   = UDim2.new(1, -36, 1, 0),
    Font                   = Enum.Font.Gotham,
    PlaceholderText        = "type a command — e.g. fly, walkspeed 50, tp Builderman",
    PlaceholderColor3      = Color3.fromRGB(110, 115, 130),
    Text                   = "",
    TextColor3             = Color3.fromRGB(230, 230, 240),
    TextSize               = 13,
    TextXAlignment         = Enum.TextXAlignment.Left,
    ClearTextOnFocus       = false,
    Parent                 = cmdBar,
})

-- ─── DRAGGABLE WINDOW (mouse + touch) ───────────────────────────────────────
do
    local dragging, dragStart, startPos
    local function begin(input)
        dragging  = true
        dragStart = input.Position
        startPos  = panel.Position
    end
    titleBar.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
        or input.UserInputType == Enum.UserInputType.Touch then
            begin(input)
            local conn
            conn = input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then
                    dragging = false
                    if conn then conn:Disconnect() end
                end
            end)
        end
    end)
    UserInputService.InputChanged:Connect(function(input)
        if not dragging then return end
        if input.UserInputType == Enum.UserInputType.MouseMovement
        or input.UserInputType == Enum.UserInputType.Touch then
            local d = input.Position - dragStart
            panel.Position = UDim2.new(
                startPos.X.Scale, startPos.X.Offset + d.X,
                startPos.Y.Scale, startPos.Y.Offset + d.Y
            )
        end
    end)
end

-- ─── TAB FACTORY ────────────────────────────────────────────────────────────
local tabs = {}                                      -- name → {button, page}
local currentTab

local function createTab(name, label)
    local btn = make("TextButton", {
        Name                   = "Tab_" .. name,
        BackgroundColor3       = Color3.fromRGB(20, 22, 28),
        BackgroundTransparency = 1,
        BorderSizePixel        = 0,
        Size                   = UDim2.new(1, 0, 0, 32),
        Font                   = Enum.Font.GothamMedium,
        Text                   = label,
        TextColor3             = Color3.fromRGB(160, 165, 180),
        TextSize               = 13,
        AutoButtonColor        = false,
        Parent                 = sidebar,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = btn })

    -- Accent strip (left side) used to mark the active tab.
    local strip = make("Frame", {
        BackgroundColor3       = CONFIG.AccentColor,
        BorderSizePixel        = 0,
        Position               = UDim2.new(0, 0, 0.5, -8),
        Size                   = UDim2.new(0, 0, 0, 16),
        Parent                 = btn,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 2), Parent = strip })

    local page = make("ScrollingFrame", {
        Name                       = "Page_" .. name,
        BackgroundTransparency     = 1,
        BorderSizePixel            = 0,
        Size                       = UDim2.fromScale(1, 1),
        Position                   = UDim2.fromOffset(0, 12),
        CanvasSize                 = UDim2.new(),
        AutomaticCanvasSize        = Enum.AutomaticSize.Y,
        ScrollBarThickness         = 3,
        ScrollBarImageColor3       = CONFIG.AccentColor,
        ScrollingDirection         = Enum.ScrollingDirection.Y,
        Visible                    = false,
        Parent                     = content,
    })
    make("UIPadding", {
        PaddingTop    = UDim.new(0, 4),  PaddingBottom = UDim.new(0, 12),
        PaddingLeft   = UDim.new(0, 12), PaddingRight  = UDim.new(0, 12),
        Parent        = page,
    })
    make("UIListLayout", {
        Padding   = UDim.new(0, 6),
        SortOrder = Enum.SortOrder.LayoutOrder,
        Parent    = page,
    })

    tabs[name] = { button = btn, page = page, strip = strip }
    btn.MouseEnter:Connect(function()
        if currentTab ~= name then
            tween(btn, QuickTween, { BackgroundTransparency = 0.4 })
        end
    end)
    btn.MouseLeave:Connect(function()
        if currentTab ~= name then
            tween(btn, QuickTween, { BackgroundTransparency = 1 })
        end
    end)
    return page
end

local function selectTab(name)
    if currentTab == name then return end
    for n, t in pairs(tabs) do
        local active = (n == name)
        t.page.Visible = active
        tween(t.button, QuickTween, {
            BackgroundTransparency = active and 0.2 or 1,
            TextColor3             = active and Color3.fromRGB(235, 235, 245)
                                              or Color3.fromRGB(160, 165, 180),
        })
        tween(t.strip, QuickTween, { Size = UDim2.new(0, active and 3 or 0, 0, 16) })
    end
    currentTab = name
end

-- ─── UI BUILDERS ────────────────────────────────────────────────────────────
local function row(parent, height)
    return make("Frame", {
        BackgroundTransparency = 1,
        Size                   = UDim2.new(1, 0, 0, height or 32),
        Parent                 = parent,
    })
end

local function sectionHeader(parent, text)
    local lbl = make("TextLabel", {
        BackgroundTransparency = 1,
        Size                   = UDim2.new(1, 0, 0, 22),
        Font                   = Enum.Font.GothamBold,
        Text                   = text:upper(),
        TextColor3             = Color3.fromRGB(120, 125, 145),
        TextSize               = 11,
        TextXAlignment         = Enum.TextXAlignment.Left,
        Parent                 = parent,
    })
    return lbl
end

local function makeToggle(parent, label, onChanged, default)
    local container = make("Frame", {
        BackgroundColor3       = Color3.fromRGB(20, 22, 28),
        BackgroundTransparency = 0.2,
        Size                   = UDim2.new(1, 0, 0, 34),
        Parent                 = parent,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = container })

    make("TextLabel", {
        BackgroundTransparency = 1,
        Position               = UDim2.new(0, 12, 0, 0),
        Size                   = UDim2.new(1, -64, 1, 0),
        Font                   = Enum.Font.GothamMedium,
        Text                   = label,
        TextColor3             = Color3.fromRGB(225, 225, 235),
        TextSize               = 13,
        TextXAlignment         = Enum.TextXAlignment.Left,
        Parent                 = container,
    })

    local track = make("Frame", {
        AnchorPoint            = Vector2.new(1, 0.5),
        Position               = UDim2.new(1, -10, 0.5, 0),
        Size                   = UDim2.fromOffset(38, 18),
        BackgroundColor3       = Color3.fromRGB(45, 48, 60),
        BorderSizePixel        = 0,
        Parent                 = container,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = track })

    local knob = make("Frame", {
        AnchorPoint            = Vector2.new(0, 0.5),
        Position               = UDim2.new(0, 2, 0.5, 0),
        Size                   = UDim2.fromOffset(14, 14),
        BackgroundColor3       = Color3.fromRGB(200, 200, 210),
        BorderSizePixel        = 0,
        Parent                 = track,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = knob })

    local btn = make("TextButton", {
        BackgroundTransparency = 1,
        Size                   = UDim2.fromScale(1, 1),
        Text                   = "",
        Parent                 = container,
    })

    local value = false
    local function set(v, fire)
        value = v
        tween(track, QuickTween, { BackgroundColor3 = v and CONFIG.AccentColor or Color3.fromRGB(45, 48, 60) })
        tween(knob,  QuickTween, {
            Position         = v and UDim2.new(1, -16, 0.5, 0) or UDim2.new(0, 2, 0.5, 0),
            BackgroundColor3 = v and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(200, 200, 210),
        })
        if fire and onChanged then onChanged(v) end
    end
    btn.MouseButton1Click:Connect(function() set(not value, true) end)
    if default then set(true, false) end
    return { container = container, set = set, get = function() return value end }
end

local function makeSlider(parent, label, min, max, default, onChanged, step)
    step = step or 1
    local container = make("Frame", {
        BackgroundColor3       = Color3.fromRGB(20, 22, 28),
        BackgroundTransparency = 0.2,
        Size                   = UDim2.new(1, 0, 0, 50),
        Parent                 = parent,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = container })
    make("UIPadding", {
        PaddingLeft = UDim.new(0, 12), PaddingRight = UDim.new(0, 12),
        PaddingTop  = UDim.new(0, 6),  PaddingBottom = UDim.new(0, 8),
        Parent = container,
    })

    local labelFrame = make("Frame", {
        BackgroundTransparency = 1,
        Size                   = UDim2.new(1, 0, 0, 18),
        Parent                 = container,
    })
    local nameLbl = make("TextLabel", {
        BackgroundTransparency = 1,
        Size                   = UDim2.new(0.6, 0, 1, 0),
        Font                   = Enum.Font.GothamMedium,
        Text                   = label,
        TextColor3             = Color3.fromRGB(225, 225, 235),
        TextSize               = 13,
        TextXAlignment         = Enum.TextXAlignment.Left,
        Parent                 = labelFrame,
    })
    local valueLbl = make("TextLabel", {
        BackgroundTransparency = 1,
        AnchorPoint            = Vector2.new(1, 0),
        Position               = UDim2.new(1, 0, 0, 0),
        Size                   = UDim2.new(0.4, 0, 1, 0),
        Font                   = Enum.Font.GothamBold,
        Text                   = tostring(default),
        TextColor3             = CONFIG.AccentColor,
        TextSize               = 13,
        TextXAlignment         = Enum.TextXAlignment.Right,
        Parent                 = labelFrame,
    })

    local track = make("Frame", {
        Position               = UDim2.new(0, 0, 0, 26),
        Size                   = UDim2.new(1, 0, 0, 6),
        BackgroundColor3       = Color3.fromRGB(35, 38, 48),
        BorderSizePixel        = 0,
        Parent                 = container,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = track })

    local fill = make("Frame", {
        Size                   = UDim2.new((default - min) / (max - min), 0, 1, 0),
        BackgroundColor3       = CONFIG.AccentColor,
        BorderSizePixel        = 0,
        Parent                 = track,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = fill })

    local value   = default
    local dragging = false

    local function updateFromX(x)
        local rel = math.clamp((x - track.AbsolutePosition.X) / track.AbsoluteSize.X, 0, 1)
        local v   = min + (max - min) * rel
        v = math.floor(v / step + 0.5) * step
        value = v
        fill.Size  = UDim2.new(rel, 0, 1, 0)
        valueLbl.Text = tostring(v)
        if onChanged then onChanged(v) end
    end

    track.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
        or input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
            updateFromX(input.Position.X)
        end
    end)
    UserInputService.InputChanged:Connect(function(input)
        if not dragging then return end
        if input.UserInputType == Enum.UserInputType.MouseMovement
        or input.UserInputType == Enum.UserInputType.Touch then
            updateFromX(input.Position.X)
        end
    end)
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
        or input.UserInputType == Enum.UserInputType.Touch then
            dragging = false
        end
    end)

    return {
        container = container,
        set       = function(v)
            value = math.clamp(v, min, max)
            fill.Size     = UDim2.new((value - min) / (max - min), 0, 1, 0)
            valueLbl.Text = tostring(value)
        end,
        get = function() return value end,
    }
end

local function makeButton(parent, label, onClick)
    local b = make("TextButton", {
        BackgroundColor3       = Color3.fromRGB(28, 30, 38),
        BackgroundTransparency = 0.1,
        BorderSizePixel        = 0,
        Size                   = UDim2.new(1, 0, 0, 32),
        Font                   = Enum.Font.GothamMedium,
        Text                   = label,
        TextColor3             = Color3.fromRGB(225, 225, 235),
        TextSize               = 13,
        AutoButtonColor        = false,
        Parent                 = parent,
    })
    make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = b })
    make("UIStroke", { Color = Color3.fromRGB(40, 44, 56), Transparency = 0.5, Parent = b })

    b.MouseEnter:Connect(function() tween(b, QuickTween, { BackgroundColor3 = CONFIG.AccentColor }) end)
    b.MouseLeave:Connect(function() tween(b, QuickTween, { BackgroundColor3 = Color3.fromRGB(28, 30, 38) }) end)
    b.MouseButton1Click:Connect(function()
        tween(b, QuickTween, { BackgroundColor3 = Color3.fromRGB(255, 255, 255) })
        task.wait(0.08)
        tween(b, QuickTween, { BackgroundColor3 = CONFIG.AccentColor })
        if onClick then onClick() end
    end)
    return b
end

-- ─── FEATURE: FLY ───────────────────────────────────────────────────────────
local function startFly()
    local char = LocalPlayer.Character
    local hrp  = getHRP(char)
    local hum  = getHumanoid(char)
    if not hrp or not hum then return end

    Active.flyBV = make("BodyVelocity", {
        MaxForce = Vector3.new(math.huge, math.huge, math.huge),
        Velocity = Vector3.zero,
        Parent   = hrp,
    })
    Active.flyBG = make("BodyGyro", {
        MaxTorque = Vector3.new(math.huge, math.huge, math.huge),
        P         = 9e4,
        CFrame    = hrp.CFrame,
        Parent    = hrp,
    })

    Active.flyConn = RunService.RenderStepped:Connect(function()
        if not Active.flyBV or not Active.flyBV.Parent then return end
        local cam = Workspace.CurrentCamera
        local dir = Vector3.zero
        if UserInputService:IsKeyDown(Enum.KeyCode.W) then dir = dir + cam.CFrame.LookVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.S) then dir = dir - cam.CFrame.LookVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.A) then dir = dir - cam.CFrame.RightVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.D) then dir = dir + cam.CFrame.RightVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.Space) then dir = dir + Vector3.new(0, 1, 0) end
        if UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) then dir = dir - Vector3.new(0, 1, 0) end
        Active.flyBV.Velocity = (dir.Magnitude > 0 and dir.Unit or Vector3.zero) * State.flySpeed
        Active.flyBG.CFrame   = cam.CFrame
    end)
    hum.PlatformStand = true
end

local function stopFly()
    if Active.flyConn then Active.flyConn:Disconnect(); Active.flyConn = nil end
    if Active.flyBV   then Active.flyBV:Destroy();      Active.flyBV   = nil end
    if Active.flyBG   then Active.flyBG:Destroy();      Active.flyBG   = nil end
    local hum = getHumanoid()
    if hum then hum.PlatformStand = false end
end

local function setFly(on)
    State.flying = on
    if on then startFly() else stopFly() end
end

-- ─── FEATURE: NOCLIP ────────────────────────────────────────────────────────
local function setNoclip(on)
    State.noclipping = on
    if Active.noclipConn then Active.noclipConn:Disconnect(); Active.noclipConn = nil end
    if on then
        Active.noclipConn = RunService.Stepped:Connect(function()
            local char = LocalPlayer.Character
            if not char then return end
            for _, d in ipairs(char:GetDescendants()) do
                if d:IsA("BasePart") and d.CanCollide then d.CanCollide = false end
            end
        end)
    end
end

-- ─── FEATURE: WALKSPEED / JUMPPOWER / INFJUMP ───────────────────────────────
local function applyWalkSpeed()
    local hum = getHumanoid()
    if not hum then return end
    hum.WalkSpeed = State.walkSpeedOn and State.walkSpeed or 16
end

local function applyJumpPower()
    local hum = getHumanoid()
    if not hum then return end
    -- Modern Humanoid uses JumpHeight when UseJumpPower=false; we toggle to power.
    hum.UseJumpPower = true
    hum.JumpPower    = State.jumpPowerOn and State.jumpPower or 50
end

local function setInfJump(on)
    State.infJump = on
    if Active.jumpConn then Active.jumpConn:Disconnect(); Active.jumpConn = nil end
    if on then
        Active.jumpConn = UserInputService.JumpRequest:Connect(function()
            local hum = getHumanoid()
            if hum then hum:ChangeState(Enum.HumanoidStateType.Jumping) end
        end)
    end
end

-- ─── FEATURE: INVISIBLE ─────────────────────────────────────────────────────
local function setInvisible(on)
    State.invisible = on
    local char = LocalPlayer.Character
    if not char then return end
    for _, d in ipairs(char:GetDescendants()) do
        if d:IsA("BasePart") then d.LocalTransparencyModifier = on and 1 or 0 end
        if d:IsA("Decal")    then d.Transparency              = on and 1 or 0 end
    end
end

-- ─── FEATURE: GOD MODE ──────────────────────────────────────────────────────
local function setGodMode(on)
    State.godMode = on
    local hum = getHumanoid()
    if not hum then return end
    if on then
        Active.godConn = hum.HealthChanged:Connect(function()
            if hum.Health < hum.MaxHealth then hum.Health = hum.MaxHealth end
        end)
        hum.MaxHealth = 1e9
        hum.Health    = 1e9
    else
        if Active.godConn then Active.godConn:Disconnect(); Active.godConn = nil end
        hum.MaxHealth = 100
        hum.Health    = 100
    end
end

-- ─── FEATURE: HEAL / RESET / SIT ────────────────────────────────────────────
local function heal()
    local hum = getHumanoid()
    if hum then hum.Health = hum.MaxHealth end
end

local function resetCharacter()
    local hum = getHumanoid()
    if hum then hum.Health = 0 end
end

local function sit()
    local hum = getHumanoid()
    if hum then hum.Sit = true end
end

-- ─── FEATURE: TELEPORT / BRING / FREEZE / SPECTATE ──────────────────────────
local function teleportToPlayer(target)
    if not target or not target.Character then return end
    local hrp       = getHRP()
    local targetHRP = target.Character:FindFirstChild("HumanoidRootPart")
    if hrp and targetHRP then
        hrp.CFrame = targetHRP.CFrame + Vector3.new(0, 0, 3)
    end
end

local function bringPlayer(target)
    if not target or not target.Character then return end
    local hrp       = getHRP()
    local targetHRP = target.Character:FindFirstChild("HumanoidRootPart")
    if hrp and targetHRP then
        targetHRP.CFrame = hrp.CFrame + Vector3.new(0, 0, 3)
    end
end

local function setFreeze(target, on)
    if not target or not target.Character then return end
    local hrp = target.Character:FindFirstChild("HumanoidRootPart")
    if not hrp then return end
    if on then
        State.frozen[target] = hrp.Anchored
        hrp.Anchored = true
    else
        hrp.Anchored = State.frozen[target] or false
        State.frozen[target] = nil
    end
end

local function setSpectate(target)
    State.spectating = target
    if target and target.Character then
        local hum = target.Character:FindFirstChildOfClass("Humanoid")
        if hum then Camera.CameraSubject = hum end
    else
        local hum = getHumanoid()
        if hum then Camera.CameraSubject = hum end
    end
end

-- ─── FEATURE: VEHICLE ───────────────────────────────────────────────────────
local function getVehicle()
    local char = LocalPlayer.Character
    if not char then return nil end
    local hum = char:FindFirstChildOfClass("Humanoid")
    if not hum then return nil end
    local seat = hum.SeatPart
    if not seat or not seat:IsA("VehicleSeat") then return nil end
    return seat:FindFirstAncestorOfClass("Model"), seat
end

local function applyVehicleSpeed()
    local _, seat = getVehicle()
    if not seat then return end
    if not seat:GetAttribute("_origMaxSpeed") then
        seat:SetAttribute("_origMaxSpeed", seat.MaxSpeed)
        seat:SetAttribute("_origTorque",   seat.Torque)
    end
    seat.MaxSpeed = seat:GetAttribute("_origMaxSpeed") * State.vehicleSpeed
    seat.Torque   = seat:GetAttribute("_origTorque")   * (State.vehicleInsta and 4 or 1)
end

local function vehicleBoost()
    local model, seat = getVehicle()
    if not model or not seat then notify("No vehicle detected", "warn"); return end
    local primary = model.PrimaryPart or seat
    primary.AssemblyLinearVelocity = primary.AssemblyLinearVelocity + primary.CFrame.LookVector * 80
end

local function setVehicleFly(on)
    State.vehicleFly = on
    if Active.vfConn then Active.vfConn:Disconnect(); Active.vfConn = nil end
    if Active.vfBV   then Active.vfBV:Destroy();      Active.vfBV   = nil end
    if Active.vfBG   then Active.vfBG:Destroy();      Active.vfBG   = nil end
    if not on then return end

    local model, seat = getVehicle()
    if not model or not seat then notify("No vehicle detected", "warn"); State.vehicleFly = false; return end
    local primary = model.PrimaryPart or seat

    Active.vfBV = make("BodyVelocity", {
        MaxForce = Vector3.new(math.huge, math.huge, math.huge),
        Velocity = Vector3.zero,
        Parent   = primary,
    })
    Active.vfBG = make("BodyGyro", {
        MaxTorque = Vector3.new(math.huge, math.huge, math.huge),
        P         = 9e4,
        CFrame    = primary.CFrame,
        Parent    = primary,
    })
    Active.vfConn = RunService.RenderStepped:Connect(function()
        if not Active.vfBV or not Active.vfBV.Parent then return end
        local cam = Workspace.CurrentCamera
        local dir = Vector3.zero
        if UserInputService:IsKeyDown(Enum.KeyCode.W) then dir = dir + cam.CFrame.LookVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.S) then dir = dir - cam.CFrame.LookVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.A) then dir = dir - cam.CFrame.RightVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.D) then dir = dir + cam.CFrame.RightVector end
        if UserInputService:IsKeyDown(Enum.KeyCode.Space)       then dir = dir + Vector3.new(0, 1, 0) end
        if UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) then dir = dir - Vector3.new(0, 1, 0) end
        Active.vfBV.Velocity = (dir.Magnitude > 0 and dir.Unit or Vector3.zero) * 80 * State.vehicleSpeed
        Active.vfBG.CFrame   = cam.CFrame
    end)
end

-- ─── FEATURE: FUN (FOV / GRAVITY / TIME / FULLBRIGHT / ESP / TRACERS) ───────
local function applyFOV()
    Camera.FieldOfView = State.fov
end

local function applyGravity()
    Workspace.Gravity = State.gravity
end

local function setTimeOfDay(tod)
    State.timeOfDay = tod
    if tod then Lighting.ClockTime = tod end
end

local FullbrightBackup = {}
local function setFullbright(on)
    State.fullbrightOn = on
    if on then
        FullbrightBackup.Ambient        = Lighting.Ambient
        FullbrightBackup.OutdoorAmbient = Lighting.OutdoorAmbient
        FullbrightBackup.Brightness     = Lighting.Brightness
        FullbrightBackup.ClockTime      = Lighting.ClockTime
        FullbrightBackup.FogEnd         = Lighting.FogEnd
        FullbrightBackup.GlobalShadows  = Lighting.GlobalShadows
        Lighting.Ambient        = Color3.fromRGB(178, 178, 178)
        Lighting.OutdoorAmbient = Color3.fromRGB(178, 178, 178)
        Lighting.Brightness     = 2
        Lighting.FogEnd         = 1e5
        Lighting.GlobalShadows  = false
    else
        for k, v in pairs(FullbrightBackup) do Lighting[k] = v end
        FullbrightBackup = {}
    end
end

local ESPInstances = {}                              -- [Player] = Highlight
local function clearESP(player)
    local h = ESPInstances[player]
    if h then h:Destroy() end
    ESPInstances[player] = nil
end

local function attachESP(player)
    if player == LocalPlayer or not player.Character then return end
    clearESP(player)
    local h = make("Highlight", {
        FillColor         = Color3.fromRGB(120, 200, 255),
        FillTransparency  = 0.6,
        OutlineColor      = Color3.fromRGB(255, 255, 255),
        OutlineTransparency = 0,
        DepthMode         = Enum.HighlightDepthMode.AlwaysOnTop,
        Adornee           = player.Character,
        Parent            = player.Character,
    })
    ESPInstances[player] = h
end

local function setESP(on)
    State.espOn = on
    if on then
        for _, p in ipairs(Players:GetPlayers()) do attachESP(p) end
    else
        for p in pairs(ESPInstances) do clearESP(p) end
    end
end

local TracerLines = {}                               -- [Player] = Frame
local function makeTracer(player)
    if player == LocalPlayer then return end
    local line = make("Frame", {
        BackgroundColor3       = Color3.fromRGB(120, 200, 255),
        BorderSizePixel        = 0,
        AnchorPoint            = Vector2.new(0.5, 0),
        Parent                 = tracerLayer,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = line })
    TracerLines[player] = line
end

local function clearTracer(player)
    local l = TracerLines[player]
    if l then l:Destroy() end
    TracerLines[player] = nil
end

local function setTracers(on)
    State.tracersOn = on
    if Active.tracerConn then Active.tracerConn:Disconnect(); Active.tracerConn = nil end
    for p in pairs(TracerLines) do clearTracer(p) end
    if not on then return end

    for _, p in ipairs(Players:GetPlayers()) do makeTracer(p) end

    Active.tracerConn = RunService.RenderStepped:Connect(function()
        local viewport = Camera.ViewportSize
        local originX, originY = viewport.X / 2, viewport.Y
        for p, line in pairs(TracerLines) do
            local char = p.Character
            local hrp  = char and char:FindFirstChild("HumanoidRootPart")
            if hrp then
                local screen, onScreen = Camera:WorldToViewportPoint(hrp.Position)
                if onScreen then
                    local dx, dy = screen.X - originX, screen.Y - originY
                    local dist   = math.sqrt(dx * dx + dy * dy)
                    line.Visible  = true
                    line.Size     = UDim2.fromOffset(2, dist)
                    line.Position = UDim2.fromOffset(originX, originY)
                    line.Rotation = math.deg(math.atan2(dy, dx)) - 90
                else
                    line.Visible = false
                end
            else
                line.Visible = false
            end
        end
    end)
end

-- ─── TABS: build pages ─────────────────────────────────────────────────────
local selfPage    = createTab("self",    "🧍  Self")
local playerPage  = createTab("players", "👥  Players")
local vehiclePage = createTab("vehicle", "🚗  Vehicle")
local funPage     = createTab("fun",     "✨  Fun")
local logPage     = createTab("logs",    "📜  Logs")
local infoPage    = createTab("info",    "⚙️  Info")

-- ── SELF tab ───────────────────────────────────────────────────────────────
sectionHeader(selfPage, "Mobility")
makeToggle(selfPage, "Fly  (W/A/S/D + Space/Ctrl)", function(v)
    setFly(v); logCmd("fly " .. tostring(v)); notify("Fly "..(v and "on" or "off"), v and "ok" or "info")
end)
makeToggle(selfPage, "Noclip", function(v)
    setNoclip(v); logCmd("noclip " .. tostring(v)); notify("Noclip "..(v and "on" or "off"), v and "ok" or "info")
end)
makeToggle(selfPage, "Infinite Jump", function(v)
    setInfJump(v); logCmd("infjump " .. tostring(v))
end)
makeSlider(selfPage, "Fly Speed", 10, 500, State.flySpeed, function(v) State.flySpeed = v end, 5)
makeSlider(selfPage, "Walk Speed", 16, 500, State.walkSpeed, function(v)
    State.walkSpeed = v; State.walkSpeedOn = true; applyWalkSpeed()
end, 1)
makeSlider(selfPage, "Jump Power", 50, 500, State.jumpPower, function(v)
    State.jumpPower = v; State.jumpPowerOn = true; applyJumpPower()
end, 5)

sectionHeader(selfPage, "Status")
makeToggle(selfPage, "Invisible", function(v) setInvisible(v); logCmd("invis " .. tostring(v)) end)
makeToggle(selfPage, "God Mode",  function(v) setGodMode(v);  logCmd("god "   .. tostring(v)) end)
makeButton(selfPage, "Heal",            function() heal();            notify("Healed", "ok") end)
makeButton(selfPage, "Reset Character", function() resetCharacter();  notify("Character reset", "info") end)
makeButton(selfPage, "Sit",             function() sit() end)

-- ── PLAYERS tab ────────────────────────────────────────────────────────────
local selectedLabel = make("TextLabel", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    BorderSizePixel        = 0,
    Size                   = UDim2.new(1, 0, 0, 28),
    Font                   = Enum.Font.GothamMedium,
    Text                   = "  Target: (none)",
    TextColor3             = Color3.fromRGB(220, 220, 230),
    TextSize               = 13,
    TextXAlignment         = Enum.TextXAlignment.Left,
    Parent                 = playerPage,
})
make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = selectedLabel })

local searchBox = make("TextBox", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    BorderSizePixel        = 0,
    Size                   = UDim2.new(1, 0, 0, 30),
    Font                   = Enum.Font.Gotham,
    PlaceholderText        = "🔍   search players…",
    PlaceholderColor3      = Color3.fromRGB(120, 125, 140),
    Text                   = "",
    TextColor3             = Color3.fromRGB(225, 225, 235),
    TextSize               = 13,
    ClearTextOnFocus       = false,
    Parent                 = playerPage,
})
make("UICorner",  { CornerRadius = UDim.new(0, 6), Parent = searchBox })
make("UIPadding", { PaddingLeft = UDim.new(0, 10), Parent = searchBox })

local playerList = make("Frame", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    BorderSizePixel        = 0,
    Size                   = UDim2.new(1, 0, 0, 150),
    Parent                 = playerPage,
})
make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = playerList })

local playerScroll = make("ScrollingFrame", {
    BackgroundTransparency = 1,
    Size                   = UDim2.fromScale(1, 1),
    BorderSizePixel        = 0,
    CanvasSize             = UDim2.new(),
    AutomaticCanvasSize    = Enum.AutomaticSize.Y,
    ScrollBarThickness     = 3,
    ScrollBarImageColor3   = CONFIG.AccentColor,
    Parent                 = playerList,
})
make("UIListLayout", { Padding = UDim.new(0, 2), Parent = playerScroll })
make("UIPadding",    {
    PaddingTop = UDim.new(0, 4), PaddingBottom = UDim.new(0, 4),
    PaddingLeft = UDim.new(0, 4), PaddingRight = UDim.new(0, 4),
    Parent = playerScroll,
})

local function setSelectedPlayer(p)
    State.selectedPlayer = p
    selectedLabel.Text = p and ("  Target: " .. p.Name .. "  (" .. p.DisplayName .. ")") or "  Target: (none)"
end

local function refreshPlayerList()
    local query = searchBox.Text:lower()
    for _, c in ipairs(playerScroll:GetChildren()) do
        if c:IsA("TextButton") then c:Destroy() end
    end
    for _, p in ipairs(Players:GetPlayers()) do
        if p ~= LocalPlayer and (query == "" or p.Name:lower():find(query, 1, true) or p.DisplayName:lower():find(query, 1, true)) then
            local btn = make("TextButton", {
                BackgroundColor3       = Color3.fromRGB(28, 30, 38),
                BackgroundTransparency = 0.2,
                BorderSizePixel        = 0,
                Size                   = UDim2.new(1, 0, 0, 26),
                Font                   = Enum.Font.GothamMedium,
                Text                   = "  " .. p.Name .. "   (" .. p.DisplayName .. ")",
                TextColor3             = Color3.fromRGB(220, 220, 230),
                TextSize               = 12,
                TextXAlignment         = Enum.TextXAlignment.Left,
                AutoButtonColor        = false,
                Parent                 = playerScroll,
            })
            make("UICorner", { CornerRadius = UDim.new(0, 4), Parent = btn })
            btn.MouseEnter:Connect(function() tween(btn, QuickTween, { BackgroundColor3 = CONFIG.AccentColor }) end)
            btn.MouseLeave:Connect(function() tween(btn, QuickTween, { BackgroundColor3 = Color3.fromRGB(28, 30, 38) }) end)
            btn.MouseButton1Click:Connect(function() setSelectedPlayer(p) end)
        end
    end
end

searchBox:GetPropertyChangedSignal("Text"):Connect(refreshPlayerList)
Players.PlayerAdded:Connect(function(p)
    refreshPlayerList()
    if State.espOn then attachESP(p) end
    if State.tracersOn then makeTracer(p) end
end)
Players.PlayerRemoving:Connect(function(p)
    refreshPlayerList()
    clearESP(p)
    clearTracer(p)
    State.frozen[p] = nil
    if State.selectedPlayer == p then setSelectedPlayer(nil) end
    if State.spectating == p then setSpectate(nil) end
end)
refreshPlayerList()

sectionHeader(playerPage, "Target actions")
local function needTarget(fn) return function() if State.selectedPlayer then fn(State.selectedPlayer) else notify("Select a player first", "warn") end end end

makeButton(playerPage, "Teleport to Player", needTarget(function(p) teleportToPlayer(p); logCmd("tp " .. p.Name); notify("Teleported to " .. p.Name, "ok") end))
makeButton(playerPage, "Bring Player",       needTarget(function(p) bringPlayer(p);       logCmd("bring " .. p.Name); notify("Brought " .. p.Name .. " (client-side)", "ok") end))
makeButton(playerPage, "Spectate Player",    needTarget(function(p) setSpectate(p);       logCmd("spec " .. p.Name); notify("Spectating " .. p.Name, "info") end))
makeButton(playerPage, "Stop Spectating",                function() setSpectate(nil);     logCmd("unspec");           notify("Spectate cleared", "info") end)
makeButton(playerPage, "View Player (jump to camera)", needTarget(function(p)
    local char = p.Character
    if char and char:FindFirstChild("HumanoidRootPart") then
        Camera.CFrame = CFrame.new(char.HumanoidRootPart.Position + Vector3.new(0, 4, 8), char.HumanoidRootPart.Position)
        notify("Viewing " .. p.Name, "info")
    end
end))
makeButton(playerPage, "Freeze Player",   needTarget(function(p) setFreeze(p, true);  logCmd("freeze "   .. p.Name); notify("Froze "   .. p.Name, "ok") end))
makeButton(playerPage, "Unfreeze Player", needTarget(function(p) setFreeze(p, false); logCmd("unfreeze " .. p.Name); notify("Unfroze " .. p.Name, "info") end))

-- ── VEHICLE tab ────────────────────────────────────────────────────────────
sectionHeader(vehiclePage, "Drive enhancement")
makeSlider(vehiclePage, "Speed Multiplier", 1, 10, 1, function(v)
    State.vehicleSpeed = v; applyVehicleSpeed()
end, 1)
makeToggle(vehiclePage, "Instant Acceleration", function(v)
    State.vehicleInsta = v; applyVehicleSpeed()
end)
makeButton(vehiclePage, "Boost (impulse)", function()
    vehicleBoost(); logCmd("vboost"); notify("Boost!", "ok")
end)
makeToggle(vehiclePage, "Vehicle Fly  (W/A/S/D + Space/Ctrl)", function(v)
    setVehicleFly(v); logCmd("vfly " .. tostring(v))
end)
makeButton(vehiclePage, "Re-detect Vehicle", function()
    local m = getVehicle()
    if m then notify("Vehicle: " .. m.Name, "ok") else notify("No vehicle detected", "warn") end
end)

-- ── FUN tab ────────────────────────────────────────────────────────────────
sectionHeader(funPage, "Camera & World")
makeSlider(funPage, "Field of View", 30, 120, State.fov, function(v) State.fov = v; applyFOV() end, 1)
makeSlider(funPage, "Gravity",       0, 400, State.gravity, function(v) State.gravity = v; applyGravity() end, 1)
makeButton(funPage, "Day",   function() setTimeOfDay(14); notify("Time → Day", "ok") end)
makeButton(funPage, "Night", function() setTimeOfDay(0);  notify("Time → Night", "info") end)

sectionHeader(funPage, "Visuals")
makeToggle(funPage, "ESP / Player Highlight", function(v) setESP(v) end)
makeToggle(funPage, "Tracers",                function(v) setTracers(v) end)
makeToggle(funPage, "Fullbright",             function(v) setFullbright(v) end)

-- ── LOGS tab ───────────────────────────────────────────────────────────────
sectionHeader(logPage, "Command history")
local logFrame = make("Frame", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    Size                   = UDim2.new(1, 0, 0, 280),
    Parent                 = logPage,
})
make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = logFrame })
local logScroll = make("ScrollingFrame", {
    BackgroundTransparency = 1,
    Size                   = UDim2.fromScale(1, 1),
    BorderSizePixel        = 0,
    CanvasSize             = UDim2.new(),
    AutomaticCanvasSize    = Enum.AutomaticSize.Y,
    ScrollBarThickness     = 3,
    ScrollBarImageColor3   = CONFIG.AccentColor,
    Parent                 = logFrame,
})
make("UIListLayout", { Padding = UDim.new(0, 2), Parent = logScroll })
make("UIPadding",    {
    PaddingTop = UDim.new(0, 6), PaddingBottom = UDim.new(0, 6),
    PaddingLeft = UDim.new(0, 8), PaddingRight = UDim.new(0, 8),
    Parent = logScroll,
})

local function refreshLogs()
    for _, c in ipairs(logScroll:GetChildren()) do
        if c:IsA("TextLabel") then c:Destroy() end
    end
    for i = #Log, 1, -1 do
        make("TextLabel", {
            BackgroundTransparency = 1,
            Size                   = UDim2.new(1, 0, 0, 16),
            Font                   = Enum.Font.Code,
            Text                   = Log[i],
            TextColor3             = Color3.fromRGB(180, 185, 200),
            TextSize               = 11,
            TextXAlignment         = Enum.TextXAlignment.Left,
            Parent                 = logScroll,
        })
    end
end

makeButton(logPage, "Clear Logs", function() table.clear(Log); refreshLogs() end)

-- Patch logCmd to refresh the log view automatically.
local _logCmd = logCmd
logCmd = function(text)
    _logCmd(text)
    if currentTab == "logs" then refreshLogs() end
end

-- ── INFO tab ───────────────────────────────────────────────────────────────
sectionHeader(infoPage, "Session")
make("TextLabel", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    Size                   = UDim2.new(1, 0, 0, 110),
    Font                   = Enum.Font.Gotham,
    Text                   = string.format([[
  Owner:        %s
  Whitelist:    %d entries
  Rank:         %s
  Keybind:      %s
  Command bar:  prefix "%s" then type a command (e.g. fly, walkspeed 100)
]],
        CONFIG.Owner == "" and "(unset — any user)" or CONFIG.Owner,
        #CONFIG.Whitelist, rank(LocalPlayer.Name),
        CONFIG.Keybind.Name, CONFIG.CommandPrefix),
    TextColor3             = Color3.fromRGB(210, 215, 225),
    TextSize               = 12,
    TextXAlignment         = Enum.TextXAlignment.Left,
    TextYAlignment         = Enum.TextYAlignment.Top,
    Parent                 = infoPage,
})
make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = infoPage:GetChildren()[#infoPage:GetChildren()] })

sectionHeader(infoPage, "Commands")
make("TextLabel", {
    BackgroundColor3       = Color3.fromRGB(20, 22, 28),
    BackgroundTransparency = 0.2,
    Size                   = UDim2.new(1, 0, 0, 240),
    Font                   = Enum.Font.Code,
    Text                   = [[
  fly                    toggle flight
  noclip                 toggle noclip
  walkspeed <n>          set walkspeed (16 = default)
  jp <n> / jumppower <n> set jump power
  infjump                toggle infinite jump
  invis / god            toggle invisibility / god mode
  heal / reset / sit     character utilities
  tp <player>            teleport to player
  bring <player>         bring player
  spec <player>          spectate (use spec off to clear)
  freeze <player>        freeze player
  unfreeze <player>      unfreeze player
  fov <n>                set field of view
  gravity <n>            set gravity
  day / night            set time of day
  esp / tracers          toggle visuals
  fullbright             toggle fullbright
  vboost                 vehicle boost
  vfly                   toggle vehicle fly
  vspeed <n>             vehicle speed multiplier
]],
    TextColor3             = Color3.fromRGB(195, 200, 215),
    TextSize               = 11,
    TextXAlignment         = Enum.TextXAlignment.Left,
    TextYAlignment         = Enum.TextYAlignment.Top,
    Parent                 = infoPage,
})
make("UICorner", { CornerRadius = UDim.new(0, 6), Parent = infoPage:GetChildren()[#infoPage:GetChildren()] })

-- Make the buttons in the sidebar actually wired now that pages exist.
for n, t in pairs(tabs) do
    t.button.MouseButton1Click:Connect(function() selectTab(n) end)
end
selectTab("self")

-- ─── COMMAND BAR ────────────────────────────────────────────────────────────
local function findPlayer(query)
    if not query or query == "" then return nil end
    query = query:lower()
    for _, p in ipairs(Players:GetPlayers()) do
        if p.Name:lower() == query then return p end
        if p.DisplayName:lower() == query then return p end
    end
    for _, p in ipairs(Players:GetPlayers()) do
        if p.Name:lower():sub(1, #query) == query then return p end
        if p.DisplayName:lower():sub(1, #query) == query then return p end
    end
    return nil
end

local function runCommand(line)
    if line == "" then return end
    if line:sub(1, #CONFIG.CommandPrefix) == CONFIG.CommandPrefix then
        line = line:sub(#CONFIG.CommandPrefix + 1)
    end
    local parts = {}
    for word in line:gmatch("%S+") do table.insert(parts, word) end
    local cmd = (parts[1] or ""):lower()
    local function arg1num(default) return tonumber(parts[2]) or default end
    local function arg1player()    return findPlayer(parts[2]) end

    if     cmd == "fly"        then setFly(not State.flying)
    elseif cmd == "unfly"      then setFly(false)
    elseif cmd == "noclip"     then setNoclip(not State.noclipping)
    elseif cmd == "clip"       then setNoclip(false)
    elseif cmd == "walkspeed"  or cmd == "ws"  then State.walkSpeed = arg1num(16); State.walkSpeedOn = true; applyWalkSpeed()
    elseif cmd == "jp" or cmd == "jumppower"   then State.jumpPower = arg1num(50); State.jumpPowerOn = true; applyJumpPower()
    elseif cmd == "infjump"    then setInfJump(not State.infJump)
    elseif cmd == "invis"      then setInvisible(not State.invisible)
    elseif cmd == "vis"        then setInvisible(false)
    elseif cmd == "god"        then setGodMode(not State.godMode)
    elseif cmd == "ungod"      then setGodMode(false)
    elseif cmd == "heal"       then heal()
    elseif cmd == "reset"      or cmd == "re" then resetCharacter()
    elseif cmd == "sit"        then sit()
    elseif cmd == "tp"         then local p = arg1player(); if p then teleportToPlayer(p) else notify("Player not found", "warn") end
    elseif cmd == "bring"      then local p = arg1player(); if p then bringPlayer(p)       else notify("Player not found", "warn") end
    elseif cmd == "spec"       then
        if parts[2] == "off" or parts[2] == nil then setSpectate(nil)
        else local p = arg1player(); if p then setSpectate(p) else notify("Player not found", "warn") end end
    elseif cmd == "freeze"     then local p = arg1player(); if p then setFreeze(p, true)  else notify("Player not found", "warn") end
    elseif cmd == "unfreeze"   then local p = arg1player(); if p then setFreeze(p, false) else notify("Player not found", "warn") end
    elseif cmd == "fov"        then State.fov     = arg1num(70);    applyFOV()
    elseif cmd == "gravity"    then State.gravity = arg1num(196.2); applyGravity()
    elseif cmd == "day"        then setTimeOfDay(14)
    elseif cmd == "night"      then setTimeOfDay(0)
    elseif cmd == "esp"        then setESP(not State.espOn)
    elseif cmd == "tracers"    then setTracers(not State.tracersOn)
    elseif cmd == "fullbright" or cmd == "fb" then setFullbright(not State.fullbrightOn)
    elseif cmd == "vboost"     then vehicleBoost()
    elseif cmd == "vfly"       then setVehicleFly(not State.vehicleFly)
    elseif cmd == "vspeed"     then State.vehicleSpeed = arg1num(1); applyVehicleSpeed()
    elseif cmd == "help"       then selectTab("info")
    else notify("Unknown command: " .. cmd, "err"); return end

    logCmd(line)
end

cmdInput.FocusLost:Connect(function(enterPressed)
    if enterPressed then
        runCommand(cmdInput.Text)
        cmdInput.Text = ""
    end
end)

-- ─── KEYBIND / OPEN-CLOSE ANIMATION ─────────────────────────────────────────
local panelOpen = false
local function setPanelVisible(open)
    if open == panelOpen then return end
    panelOpen = open
    if open then
        panel.Visible        = true
        panel.Size           = UDim2.fromOffset(0, 0)
        panel.BackgroundTransparency = 1
        tween(panel, BounceTween, {
            Size                   = UDim2.fromOffset(620, 420),
            BackgroundTransparency = 0.05,
        })
    else
        local t = tween(panel, QuickTween, {
            Size                   = UDim2.fromOffset(0, 0),
            BackgroundTransparency = 1,
        })
        t.Completed:Connect(function() panel.Visible = false end)
    end
end

closeBtn.MouseButton1Click:Connect(function() setPanelVisible(false) end)

local minimized = false
minimizeBtn.MouseButton1Click:Connect(function()
    minimized = not minimized
    if minimized then
        tween(panel, QuickTween, { Size = UDim2.fromOffset(620, 40) })
        sidebar.Visible = false; content.Visible = false; cmdBar.Visible = false
    else
        sidebar.Visible = true;  content.Visible = true;  cmdBar.Visible = true
        tween(panel, QuickTween, { Size = UDim2.fromOffset(620, 420) })
    end
end)

UserInputService.InputBegan:Connect(function(input, processed)
    if processed then return end
    if input.KeyCode == CONFIG.Keybind then
        setPanelVisible(not panelOpen)
    end
end)

-- ─── MOBILE TOGGLE BUTTON ───────────────────────────────────────────────────
if CONFIG.ShowMobileButton and UserInputService.TouchEnabled and not UserInputService.MouseEnabled then
    local mobileBtn = make("TextButton", {
        Name                   = "MobileToggle",
        AnchorPoint            = Vector2.new(0, 0.5),
        Position               = UDim2.new(0, 8, 0.35, 0),
        Size                   = UDim2.fromOffset(54, 54),
        BackgroundColor3       = CONFIG.AccentColor,
        BackgroundTransparency = 0.1,
        BorderSizePixel        = 0,
        Font                   = Enum.Font.GothamBold,
        Text                   = "≡",
        TextColor3             = Color3.fromRGB(255, 255, 255),
        TextSize               = 28,
        AutoButtonColor        = false,
        Parent                 = gui,
    })
    make("UICorner", { CornerRadius = UDim.new(1, 0), Parent = mobileBtn })
    make("UIStroke", { Color = Color3.fromRGB(255, 255, 255), Transparency = 0.6, Parent = mobileBtn })
    mobileBtn.MouseButton1Click:Connect(function() setPanelVisible(not panelOpen) end)

    -- Make the floating button draggable on touch.
    local dragging, dragStart, startPos
    mobileBtn.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.Touch then
            dragging = true; dragStart = input.Position; startPos = mobileBtn.Position
        end
    end)
    UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.Touch then
            local d = input.Position - dragStart
            mobileBtn.Position = UDim2.new(
                startPos.X.Scale, startPos.X.Offset + d.X,
                startPos.Y.Scale, startPos.Y.Offset + d.Y
            )
        end
    end)
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.Touch then dragging = false end
    end)
end

-- ─── RESPAWN HANDLING ───────────────────────────────────────────────────────
-- When the local character respawns, every toggled feature has to be
-- re-applied since the old Humanoid / BodyMovers are gone.
LocalPlayer.CharacterAdded:Connect(function(char)
    char:WaitForChild("HumanoidRootPart")
    char:WaitForChild("Humanoid")
    task.wait(0.1)
    if State.flying       then startFly() end
    if State.noclipping   then setNoclip(true) end
    if State.walkSpeedOn  then applyWalkSpeed() end
    if State.jumpPowerOn  then applyJumpPower() end
    if State.invisible    then setInvisible(true) end
    if State.godMode      then setGodMode(true) end
    if State.spectating and State.spectating.Parent then setSpectate(State.spectating) end
end)

LocalPlayer.CharacterRemoving:Connect(function()
    -- Drop the per-character BodyMover refs so the new character starts clean.
    if Active.flyConn then Active.flyConn:Disconnect(); Active.flyConn = nil end
    Active.flyBV = nil; Active.flyBG = nil
    if Active.godConn then Active.godConn:Disconnect(); Active.godConn = nil end
end)

-- Re-bind Camera reference on camera swaps so we always operate on the live one.
Workspace:GetPropertyChangedSignal("CurrentCamera"):Connect(function()
    Camera = Workspace.CurrentCamera
    Camera.FieldOfView = State.fov
end)

-- ─── PLAYER LIST AUTOREFRESH ────────────────────────────────────────────────
-- Refresh tracer/ESP for newly added characters as well.
Players.PlayerAdded:Connect(function(p)
    p.CharacterAdded:Connect(function()
        task.wait(0.5)
        if State.espOn     then attachESP(p) end
        if State.tracersOn then makeTracer(p) end
    end)
end)
for _, p in ipairs(Players:GetPlayers()) do
    if p ~= LocalPlayer then
        p.CharacterAdded:Connect(function()
            task.wait(0.5)
            if State.espOn     then attachESP(p) end
            if State.tracersOn then makeTracer(p) end
        end)
    end
end

-- ─── BOOT ───────────────────────────────────────────────────────────────────
applyFOV()
applyGravity()
notify("Admin Panel ready — press " .. CONFIG.Keybind.Name, "ok")
